### ISSUE TITLE
Weekly Scrum - March 8th to March 12th

### ISSUE THREAD

**Issue by mrunal-patel1997** [RhysMelanson/SYSC_4806_Survey_Monkey#12]
Each week a group member should open a new issue called Weekly scrum – [date], then every team
member should add comments with their own contribution, i.e. their answers to the questions:
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)
Expected length: 1-2 sentences per item.

**Comment by RhysMelanson** [comment]
What I did this week
-I set up the git hub
-Set up the Travis CI #14 
-Got the repos working so that they can now store data #13 

What will I do next week
-I plan on updating the repos to more coherently store the data in specific formats and make questions visible when someone opens the page

What is holding me back
-Prior commitments to other courses group projects

**Comment by mrunal-patel1997** [comment]
What I did this week
- I created the Jira Board #16

What will I do next week 
- I plan on implementing integration testing
- I plan on implementing front-end testing for our presentation (Jasmine). 

What is holding me back
- I have to do some preliminary research on how to implement front-end testing.
- I also need to ensure that our project has features implemented/features planned out that I can write test drivers/stubs for. 
- Prior commitments to the fourth-year project.

**Comment by andrewehatt** [comment]
What I did this week

- I made the repository able to save using REST

What I will do next week:

- I will implement the REST functionality for the other features to come

What is holding me back:

- Not sure how to get the controller to both display the appropriate template and save to the repository
- Unfamiliar with HTML

**Comment by HassanAYusuf** [comment]
What I did this week
- I provided a base project and fixed the backend to suite the survey application https://github.com/RhysMelanson/SYSC_4806_Survey_Monkey/issues/5 https://github.com/RhysMelanson/SYSC_4806_Survey_Monkey/issues/3
- I helped in the set up of the travis.yml and heroku

What I will do next week:
- I will fix the front end to be more logical and work on a few more functionalities
- I will implement an interface for the answers class to implement different types of ansewers

What is holding me back:
I am unfamiliar with testing the front end and using javascript in the spring framework

**Comment by NRA3110** [comment]
What I did this week:

- Created test files for QuestionInfo and Survey
- Added test cases for each test file

What I will do next week:

- Create test files for any further files created in this sprint
- Create additional backend tests for new and existing classes

What is holding me back:
Unfamiliar with HTML
Further commitments to other group projects
